//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using Entidades;
    public partial class RTEntities : DbContext
    {
        public RTEntities()
            : base("name=RTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<menu> menus { get; set; }
        public virtual DbSet<mesa> mesas { get; set; }
        public virtual DbSet<reservacione> reservaciones { get; set; }
        public virtual DbSet<vw_HistorialReservaciones> vw_HistorialReservaciones { get; set; }
        public virtual DbSet<vw_MenuPrecios> vw_MenuPrecios { get; set; }
        public virtual DbSet<vw_OcupacionMesas> vw_OcupacionMesas { get; set; }
        public virtual DbSet<vw_ReservacionesDetalles> vw_ReservacionesDetalles { get; set; }
    
        public virtual int PA_delCliente(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_delCliente", idParameter);
        }
    
        public virtual int PA_delMenu(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_delMenu", idParameter);
        }
    
        public virtual int PA_delMesa(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_delMesa", idParameter);
        }
    
        public virtual int PA_delReservacion(Nullable<int> numero_reservacion)
        {
            var numero_reservacionParameter = numero_reservacion.HasValue ?
                new ObjectParameter("numero_reservacion", numero_reservacion) :
                new ObjectParameter("numero_reservacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_delReservacion", numero_reservacionParameter);
        }
    
        public virtual int PA_insCliente(string nombre, string apellidos, string telefono, string correo)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidosParameter = apellidos != null ?
                new ObjectParameter("apellidos", apellidos) :
                new ObjectParameter("apellidos", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_insCliente", nombreParameter, apellidosParameter, telefonoParameter, correoParameter);
        }
    
        public virtual int PA_insMenu(string descripcion, Nullable<decimal> precio)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_insMenu", descripcionParameter, precioParameter);
        }
    
        public virtual int PA_insMesa(Nullable<int> numero_mesa, string descripcion)
        {
            var numero_mesaParameter = numero_mesa.HasValue ?
                new ObjectParameter("numero_mesa", numero_mesa) :
                new ObjectParameter("numero_mesa", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_insMesa", numero_mesaParameter, descripcionParameter);
        }
    
        public virtual int PA_insReservacion(Nullable<int> id_cliente, Nullable<int> numero_mesa, Nullable<int> id_menu, Nullable<int> cantidad, Nullable<System.DateTime> fecha_reservacion)
        {
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            var numero_mesaParameter = numero_mesa.HasValue ?
                new ObjectParameter("numero_mesa", numero_mesa) :
                new ObjectParameter("numero_mesa", typeof(int));
    
            var id_menuParameter = id_menu.HasValue ?
                new ObjectParameter("id_menu", id_menu) :
                new ObjectParameter("id_menu", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            var fecha_reservacionParameter = fecha_reservacion.HasValue ?
                new ObjectParameter("fecha_reservacion", fecha_reservacion) :
                new ObjectParameter("fecha_reservacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_insReservacion", id_clienteParameter, numero_mesaParameter, id_menuParameter, cantidadParameter, fecha_reservacionParameter);
        }
    
        public virtual int PA_modCliente(Nullable<int> id, string nombre, string apellidos, string telefono, string correo)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidosParameter = apellidos != null ?
                new ObjectParameter("apellidos", apellidos) :
                new ObjectParameter("apellidos", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_modCliente", idParameter, nombreParameter, apellidosParameter, telefonoParameter, correoParameter);
        }
    
        public virtual int PA_modMenu(Nullable<int> id, string descripcion, Nullable<decimal> precio)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_modMenu", idParameter, descripcionParameter, precioParameter);
        }
    
        public virtual int PA_modMesa(Nullable<int> id, Nullable<int> numero_mesa, string descripcion)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var numero_mesaParameter = numero_mesa.HasValue ?
                new ObjectParameter("numero_mesa", numero_mesa) :
                new ObjectParameter("numero_mesa", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_modMesa", idParameter, numero_mesaParameter, descripcionParameter);
        }
    
        public virtual int PA_modReservacion(Nullable<int> numero_reservacion, Nullable<int> id_cliente, Nullable<int> numero_mesa, Nullable<int> id_menu, Nullable<int> cantidad, Nullable<System.DateTime> fecha_reservacion)
        {
            var numero_reservacionParameter = numero_reservacion.HasValue ?
                new ObjectParameter("numero_reservacion", numero_reservacion) :
                new ObjectParameter("numero_reservacion", typeof(int));
    
            var id_clienteParameter = id_cliente.HasValue ?
                new ObjectParameter("id_cliente", id_cliente) :
                new ObjectParameter("id_cliente", typeof(int));
    
            var numero_mesaParameter = numero_mesa.HasValue ?
                new ObjectParameter("numero_mesa", numero_mesa) :
                new ObjectParameter("numero_mesa", typeof(int));
    
            var id_menuParameter = id_menu.HasValue ?
                new ObjectParameter("id_menu", id_menu) :
                new ObjectParameter("id_menu", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            var fecha_reservacionParameter = fecha_reservacion.HasValue ?
                new ObjectParameter("fecha_reservacion", fecha_reservacion) :
                new ObjectParameter("fecha_reservacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_modReservacion", numero_reservacionParameter, id_clienteParameter, numero_mesaParameter, id_menuParameter, cantidadParameter, fecha_reservacionParameter);
        }
    
        public virtual ObjectResult<PA_recCliente_Result> PA_recCliente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_recCliente_Result>("PA_recCliente");
        }
    
        public virtual ObjectResult<PA_recClienteXId_Result> PA_recClienteXId(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_recClienteXId_Result>("PA_recClienteXId", idParameter);
        }
    
        public virtual ObjectResult<PA_recMenu_Result> PA_recMenu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_recMenu_Result>("PA_recMenu");
        }
    
        public virtual ObjectResult<PA_recMenuXId_Result> PA_recMenuXId(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_recMenuXId_Result>("PA_recMenuXId", idParameter);
        }
    
        public virtual ObjectResult<PA_recMesa_Result> PA_recMesa()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_recMesa_Result>("PA_recMesa");
        }
    
        public virtual ObjectResult<PA_recMesaXId_Result> PA_recMesaXId(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_recMesaXId_Result>("PA_recMesaXId", idParameter);
        }
    
        public virtual ObjectResult<PA_recReservacion_Result> PA_recReservacion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_recReservacion_Result>("PA_recReservacion");
        }
    
        public virtual ObjectResult<PA_recReservacionXId_Result> PA_recReservacionXId(Nullable<int> numero_reservacion)
        {
            var numero_reservacionParameter = numero_reservacion.HasValue ?
                new ObjectParameter("numero_reservacion", numero_reservacion) :
                new ObjectParameter("numero_reservacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_recReservacionXId_Result>("PA_recReservacionXId", numero_reservacionParameter);
        }
    }
}
