//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservacione
    {
        public int numero_reservacion { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> numero_mesa { get; set; }
        public Nullable<int> id_menu { get; set; }
        public int cantidad { get; set; }
        public System.DateTime fecha_reservacion { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual menu menu { get; set; }


    }
}
